#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Automation_Game.Resource", IsApplication=true)]

namespace Automation_Game
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int craft = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int inventory_icon = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int inventory_slot_border = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int mainmenu_background = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int map_icon = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int proccess_bar_empty = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int proccess_bar_filled = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int settings = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int sprite_sheet = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int turn_right = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int access_layout = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int backdrop = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int craftingMenu = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int debug = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int frame = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int input = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int last = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int main = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int openInventory = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int openMap = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int output = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int relativeLayout1 = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int slot1 = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int slot2 = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int slot3 = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int slot4 = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int slot5 = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int slot6 = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int slot7 = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int slot8 = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int slotEquip = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int slotsLayout1 = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int slotsLayout2 = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int start = 2130903063;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int game_map = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int inventory_layout = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int proccessing_layout = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int startup_menu = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int action_settings = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int load = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int start = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
